(deftheme polar-bear
  "Simple almost monochrome theme based on Nord.")

(custom-theme-set-faces
 'polar-bear
 '(cursor ((t (:background "#FFFFFF"))))
 '(escape-glyph ((t (:foreground "#BF616A"))))
 '(homoglyph ((t (:foreground "#EBCB8B"))))
 '(minibuffer-prompt ((t (:inherit (modus-themes-prompt)))))
 '(highlight ((t (:foreground "#D8DEE9" :background "#4C566A"))))
 '(region ((t (:extend t :foreground "#D8DEE9" :background "#3B4252"))))
 '(shadow ((t (:foreground "#B4B4BE"))))
 '(secondary-selection ((t (:extend t :foreground "#D8DEE9" :background "#654a39"))))
 '(trailing-whitespace ((t (:background "#9d1f1f"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#D8DEE9" :inherit (modus-themes-bold)))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#88C0D0" :inherit (modus-themes-slant)))))
 '(font-lock-constant-face ((t (:foreground "#D8DEE9"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#D8DEE9" :inherit (modus-themes-slant)))))
 '(font-lock-doc-markup-face ((t (:foreground "#D8DEE9" :inherit (modus-themes-slant)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#D8DEE9"))))
 '(font-lock-keyword-face ((t (:foreground "#D8DEE9" :inherit (modus-themes-bold)))))
 '(font-lock-negation-char-face ((t (:inherit (error)))))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#D8DEE9"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#D8DEE9" :inherit (modus-themes-bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#D8DEE9" :inherit (modus-themes-bold)))))
 '(font-lock-string-face ((t (:foreground "#ffffff"))))
 '(font-lock-type-face ((t (:foreground "#D8DEE9" :inherit (modus-themes-bold)))))
 '(font-lock-variable-name-face ((t (:foreground "#D8DEE9"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "#EBCB8B" :inherit (modus-themes-bold)))))
 '(button ((t (:underline (:color "#4C566A" :style line :position nil) :foreground "#81A1C1"))))
 '(link ((t (:inherit (button)))))
 '(link-visited ((t (:underline (:color "#4C566A" :style line :position nil) :foreground "#B48EAD"))))
 '(fringe ((t (:foreground "#D8DEE9"))))
 '(header-line ((t (:background "#3B4352" :inherit (modus-themes-ui-variable-pitch)))))
 '(tooltip ((t (:foreground "#D8DEE9" :background "#4C566A"))))
 '(mode-line ((t (:box (:line-width (1 . 1) :color "#4C566A" :style nil) :foreground "#E5E9F0" :background "#4C566A" :inherit (modus-themes-ui-variable-pitch)))))
 '(mode-line-buffer-id ((t (:inherit (bold)))))
 '(mode-line-emphasis ((t (:foreground "#9fefff" :inherit (bold)))))
 '(mode-line-highlight ((t (:box (:line-width (1 . 1) :color "#D8DEE9" :style nil) :foreground "#D8DEE9" :background "#4C566A"))))
 '(mode-line-inactive ((t (:box (:line-width (1 . 1) :color "#81A1C1" :style nil) :foreground "#81A1C1" :background "#2E3440" :inherit (modus-themes-ui-variable-pitch)))))
 '(isearch ((t (:inherit (modus-themes-search-current)))))
 '(isearch-fail ((t (:inherit (modus-themes-prominent-error)))))
 '(lazy-highlight ((t (:inherit (modus-themes-search-lazy)))))
 '(match ((t (:foreground "#D8DEE9" :background "#552f5f"))))
 '(next-error ((t (:extend t :inherit (modus-themes-prominent-error)))))
 '(query-replace ((t (:inherit (modus-themes-search-replace))))))

(provide-theme 'polar-bear)

;; (setq modus-vivendi-palette-overrides ;; this is the light theme
;;       '(;; colors
;;         (red             "#BF616A")
;;         (red-warmer      "#BF616A")
;;         (red-cooler      "#BF616A")
;;         (red-faint       "#BF616A")
;;         (red-intense     "#BF616A")
;;         (green           "#A3BE8C")
;;         (green-warmer    "#A3BE8C")
;;         (green-cooler    "#A3BE8C")
;;         (green-faint     "#A3BE8C")
;;         (green-intense   "#A3BE8C")
;;         (yellow          "#EBCB8B")
;;         (yellow-warmer   "#EBCB8B")
;;         (yellow-cooler   "#EBCB8B")
;;         (yellow-faint    "#EBCB8B")
;;         (yellow-intense  "#EBCB8B")
;;         (blue            "#81A1C1")
;;         (blue-warmer     "#81A1C1")
;;         (blue-cooler     "#81A1C1")
;;         (blue-faint      "#81A1C1")
;;         (blue-intense    "#81A1C1")
;;         (magenta         "#B48EAD")
;;         (magenta-warmer  "#B48EAD")
;;         (magenta-cooler  "#B48EAD")
;;         (magenta-faint   "#B48EAD")
;;         (magenta-intense "#B48EAD")
;;         (cyan            "#87C0D0")
;;         (cyan-warmer     "#87C0D0")
;;         (cyan-cooler     "#87C0D0")
;;         (cyan-faint      "#87C0D0")
;;         (cyan-intense    "#87C0D0")
;;         (rust            "#D08770")
;;         (gold            "#EBCB8B")
;;         (olive           "#647D4A")
;;         (slate           "#4B647D")
;;         (indigo          "#D5BBCF")
;;         (maroon          "#AD8CAE")
;;         (pink            "#EDDAEB")
;;         ;; emacs parts
;;         (cursor      "#FFFFFF")
;;         ;; bg
;;         (bg-main     "#2E3440")
;;         (bg-dim      "#3B4352")
;;         (bg-active   "#4C566A")
;;         (bg-inactive "#535D72")
;;         (border      "#4C566A")
;;         (bg-completion bg-active)
;;         (bg-hover bg-active)
;;         (bg-hl-line bg-dim)
;;         ;; fg
;;         (fg-main     "#D8DEE9")
;;         (fg-dim      "#B4B4BE")
;;         (fg-alt      "#D8ECF2")
;;         ;; modeline
;;         (bg-mode-line-active   "#4C566A")
;;         (fg-mode-line-active   "#E5E9F0")
;;         (bg-mode-line-inactive bg-main)
;;         (fg-mode-line-inactive "#81A1C1")
;;         (border-mode-line-active "#4C566A")
;;         (border-mode-line-inactive "#81A1C1")
;;         (bg-line-number-inactive bg-main)
;;         (fg-line-number-inactive "#4C566A")
;;         (bg-line-number-active bg-main)
;;         (fg-line-number-active fg-main)
;;         ;; icons in the fringe
;;         (fg-prominent-err     "#BF616A")
;;         (bg-prominent-err bg-main)
;;         (fg-prominent-warning "#AE7504")
;;         (bg-prominent-warning bg-main)
;;         (fg-prominent-note    "#0063A9")
;;         (bg-prominent-note bg-main)
;;         ;; parenthesis match
;;         (bg-paren-match "#88C0D0")
;;         (fg-paren-match bg-main)
;;         ;; selection
;;         (bg-region "#3B4252")
;;         (fg-region fg-main)
;;         ;; code parts
;;         (comment "#88C0D0")
;;         (string  "#ffffff")
;;         (builtin      fg-main)
;;         (constant     fg-main)
;;         (docstring    fg-main)
;;         (docmarkup    fg-main)
;;         (fnname       fg-main)
;;         (keyword      fg-main)
;;         (preprocessor fg-main)
;;         (type         fg-main)
;;         (variable     fg-main)
;;         (rx-construct fg-main)
;;         (rx-backslash fg-main)
;;         ))
