(deftheme steam-engine
  "Simple theme loosely based on Steam client colors from 2003.")

(custom-theme-set-faces
 'steam-engine
 '(cursor ((t (:background "#FFFFFF"))))
 '(escape-glyph ((t (:foreground "#DA3131"))))
 '(homoglyph ((t (:foreground "#D2C646"))))
 '(minibuffer-prompt ((t (:inherit (modus-themes-prompt)))))
 '(highlight ((t (:foreground "#EBEFE7" :background "#4C5844"))))
 '(region ((t (:extend t :foreground "#EBEFE7" :background "#67745D"))))
 '(shadow ((t (:foreground "#ABB49E"))))
 '(secondary-selection ((t (:extend t :foreground "#EBEFE7" :background "#654a39"))))
 '(trailing-whitespace ((t (:background "#9d1f1f"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#EBEFE7" :inherit (modus-themes-bold)))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#D2C646" :inherit (modus-themes-slant)))))
 '(font-lock-constant-face ((t (:foreground "#EBEFE7"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#EBEFE7" :inherit (modus-themes-slant)))))
 '(font-lock-doc-markup-face ((t (:foreground "#EBEFE7" :inherit (modus-themes-slant)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#EBEFE7"))))
 '(font-lock-keyword-face ((t (:foreground "#EBEFE7" :inherit (modus-themes-bold)))))
 '(font-lock-negation-char-face ((t (:inherit (error)))))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#EBEFE7"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#EBEFE7" :inherit (modus-themes-bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#EBEFE7" :inherit (modus-themes-bold)))))
 '(font-lock-string-face ((t (:foreground "#EFF5C7"))))
 '(font-lock-type-face ((t (:foreground "#EBEFE7" :inherit (modus-themes-bold)))))
 '(font-lock-variable-name-face ((t (:foreground "#EBEFE7"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "#D2C646" :inherit (modus-themes-bold)))))
 '(button ((t (:underline (:color "#4C5844" :style line :position nil) :foreground "#D2C646"))))
 '(link ((t (:inherit (button)))))
 '(link-visited ((t (:underline (:color "#4C5844" :style line :position nil) :foreground "#DD8B20"))))
 '(fringe ((t (:foreground "#EBEFE7"))))
 '(header-line ((t (:background "#282E22" :inherit (modus-themes-ui-variable-pitch)))))
 '(tooltip ((t (:foreground "#EBEFE7" :background "#4C5844"))))
 '(mode-line ((t (:box (:line-width (1 . 1) :color "#939C87" :style nil) :foreground "#ffffff" :background "#5B6950" :inherit (modus-themes-ui-variable-pitch)))))
 '(mode-line-buffer-id ((t (:inherit (bold)))))
 '(mode-line-emphasis ((t (:foreground "#9fefff" :inherit (bold)))))
 '(mode-line-highlight ((t (:box (:line-width (1 . 1) :color "#EBEFE7" :style nil) :foreground "#EBEFE7" :background "#4C5844"))))
 '(mode-line-inactive ((t (:box (:line-width (1 . 1) :color "#282E22" :style nil) :foreground "#8A8E83" :background "#282E22" :inherit (modus-themes-ui-variable-pitch)))))
 '(isearch ((t (:inherit (modus-themes-search-current)))))
 '(isearch-fail ((t (:inherit (modus-themes-prominent-error)))))
 '(lazy-highlight ((t (:inherit (modus-themes-search-lazy)))))
 '(match ((t (:foreground "#EBEFE7" :background "#552f5f"))))
 '(next-error ((t (:extend t :inherit (modus-themes-prominent-error)))))
 '(query-replace ((t (:inherit (modus-themes-search-replace))))))

(provide-theme 'steam-engine)

;; (setq modus-vivendi-palette-overrides ;; this is the light theme
;;       '(;; colors
;;         (red             "#DA3131")
;;         (red-warmer      "#DA3131")
;;         (red-cooler      "#DA3131")
;;         (red-faint       "#DA3131")
;;         (red-intense     "#DA3131")
;;         (green           "#90B063")
;;         (green-warmer    "#90B063")
;;         (green-cooler    "#90B063")
;;         (green-faint     "#90B063")
;;         (green-intense   "#90B063")
;;         (yellow          "#D2C646")
;;         (yellow-warmer   "#D2C646")
;;         (yellow-cooler   "#D2C646")
;;         (yellow-faint    "#D2C646")
;;         (yellow-intense  "#D2C646")
;;         (blue            "#D2C646")
;;         (blue-warmer     "#D2C646")
;;         (blue-cooler     "#D2C646")
;;         (blue-faint      "#D2C646")
;;         (blue-intense    "#D2C646")
;;         (magenta         "#DD8B20")
;;         (magenta-warmer  "#DD8B20")
;;         (magenta-cooler  "#DD8B20")
;;         (magenta-faint   "#DD8B20")
;;         (magenta-intense "#DD8B20")
;;         (cyan            "#D2C646")
;;         (cyan-warmer     "#D2C646")
;;         (cyan-cooler     "#D2C646")
;;         (cyan-faint      "#D2C646")
;;         (cyan-intense    "#D2C646")
;;         (rust            "#D57C55")
;;         (gold            "#EBCB8B")
;;         (olive           "#AFD685")
;;         (slate           "#D2C646")
;;         (indigo          "#DD8B20")
;;         (maroon          "#DD8B20")
;;         (pink            "#DD8B20")
;;         ;; emacs parts
;;         (cursor      "#FFFFFF")
;;         ;; bg
;;         (bg-main     "#3F4537")
;;         (bg-dim      "#282E22")
;;         (bg-active   "#4C5844")
;;         (bg-inactive "#5B6950")
;;         (border      "#8A8E83")
;;         (bg-completion bg-active)
;;         (bg-hover bg-active)
;;         (bg-hl-line bg-dim)
;;         ;; fg
;;         (fg-main     "#EBEFE7")
;;         (fg-dim      "#ABB49E")
;;         (fg-alt      "#D2C646")
;;         ;; modeline
;;         (bg-mode-line-active   "#5B6950")
;;         (fg-mode-line-active   "#ffffff")
;;         (bg-mode-line-inactive "#282E22")
;;         (fg-mode-line-inactive "#8A8E83")
;;         (border-mode-line-active "#939C87")
;;         (border-mode-line-inactive "#282E22")
;;         (bg-line-number-inactive bg-main)
;;         (fg-line-number-inactive "#5F6656")
;;         (bg-line-number-active bg-main)
;;         (fg-line-number-active fg-main)
;;         ;; icons in the fringe
;;         (fg-prominent-err     "#DA3131")
;;         (bg-prominent-err bg-main)
;;         (fg-prominent-warning "#CE9E3F")
;;         (bg-prominent-warning bg-main)
;;         (fg-prominent-note    "#0063A9")
;;         (bg-prominent-note bg-main)
;;         ;; parenthesis match
;;         (bg-paren-match "#D2C646")
;;         (fg-paren-match bg-main)
;;         ;; selection
;;         (bg-region "#67745D")
;;         (fg-region fg-main)
;;         ;; code parts
;;         (comment "#D2C646")
;;         (string  "#EFF5C7")
;;         (builtin      fg-main)
;;         (constant     fg-main)
;;         (docstring    fg-main)
;;         (docmarkup    fg-main)
;;         (fnname       fg-main)
;;         (keyword      fg-main)
;;         (preprocessor fg-main)
;;         (type         fg-main)
;;         (variable     fg-main)
;;         (rx-construct fg-main)
;;         (rx-backslash fg-main)
;;         ))
