;;; proj.el --- Project discovery and the known-project list -*- lexical-binding: t; -*-

;;; Commentary:
;; project.el extras: manual list + auto-discover scan, depth control.

;;; Code:

(eval-when-compile (require 'project))

;; These three are not autoloaded, so the compiler cannot know the runtime
(declare-function project--read-project-list "project")
(declare-function project--remember-dir "project")
(declare-function project--clear-cache "project")
(declare-function project-prompt-project-dir "project")

;;;; Settings

(defvar my/project-search-paths
  '("~/projects" "~/src" "~/dotfiles" "~/notes")
  "Where `my/project-discover' looks for projects. Each entry is a directory, or a cons (DIRECTORY . MAX-DEPTH) to cap how far below that one directory the scan may go. Uncapped entries use `my/project-scan-max-depth'.")

(defvar my/project-scan-max-depth nil
  "How deep `my/project-discover' descends, or nil for no limit. No limit is the sensible default because the scan stops at the first project root it finds -- so the only directories it ever walks are the non-repository ones sitting above your repositories, of which there are a handful. Skipping is what keeps the scan cheap, not depth; see `my/project-scan-prune'.")

(defvar my/project-auto-file
  (expand-file-name "projects-auto.eld" user-emacs-directory)
  "File holding the roots found by `my/project-discover'.")

(defvar my/project-root-markers
  '(".git" ".hg" ".svn" ".bzr" ".jj" "_darcs")
  "Files or directories whose presence makes a directory a project root.")

(defvar my/project-scan-prune
  '("node_modules" "elpa" "eln-cache" "straight" "\\.cache"
    "venv" "__pycache__" "site-packages" "\\.tox"
    "target" "build" "_build" "dist" "out" "vendor" "third_party"
    "plugged" "pack" "Pods" "Carthage" "DerivedData"
    "Library" "Applications" "Trash")
  "Directory names `my/project-discover' never descends into. Each entry is a regexp anchored to the whole name, so \"elpa\".")

(defvar my/project--prune-cache nil
  "Cons of (PRUNE-LIST . REGEXP), so the regexp is rebuilt only when needed.")

(defun my/project--prune-regexp ()
  "Return a regexp matching any whole name in `my/project-scan-prune'."
  (unless (equal (car my/project--prune-cache) my/project-scan-prune)
    (setq my/project--prune-cache
          (cons (copy-sequence my/project-scan-prune)
                (concat "\\`\\(?:"
                        (mapconcat #'identity my/project-scan-prune "\\|")
                        "\\)\\'"))))
  (cdr my/project--prune-cache))

;;;; Merging the generated list into the hand-edited one

(defvar my/project--auto-only nil
  "Roots that came from `my/project-auto-file' and are not in `project-list-file'.")

(defun my/project--normalize (root)
  "Return ROOT in the shape `project.el' stores roots in."
  (file-name-as-directory (abbreviate-file-name (expand-file-name root))))

(defun my/project--read-auto-roots ()
  "Return the list of roots stored in `my/project-auto-file'."
  (when (file-exists-p my/project-auto-file)
    (with-temp-buffer
      (insert-file-contents my/project-auto-file)
      (condition-case nil
          (mapcar (lambda (elem)
                    (my/project--normalize (if (consp elem) (car elem) elem)))
                  (read (current-buffer)))
        (error
         (warn "Ignoring %s: not a readable project list" my/project-auto-file)
         nil)))))

(defun my/project--write-auto-roots (roots)
  "Write ROOTS to `my/project-auto-file'."
  (with-temp-file my/project-auto-file
    (insert ";;; -*- lisp-data -*-\n"
            ";; Generated by `my/project-discover' -- every scan overwrites this\n"
            ";; file, so edits here do not survive.  Hand-curated projects belong\n"
            ";; in `project-list-file'; open that one with `my/edit-projects'.\n")
    (let ((print-length nil)
          (print-level nil))
      (pp (mapcar (lambda (root) (list (expand-file-name root))) roots)
          (current-buffer)))))

(defun my/project--merge-auto (&rest _)
  "Append the generated roots to `project--list'."
  (let ((manual (mapcar #'car project--list)))
    (setq my/project--auto-only
          (seq-remove (lambda (root) (member root manual))
                      (my/project--read-auto-roots)))
    (setq project--list
          (append project--list (mapcar #'list my/project--auto-only)))))

(defun my/project--write-manual-only (fn &rest args)
  "Call FN with ARGS, hiding generated roots from `project--list'."
  (let ((project--list
         (seq-remove (lambda (entry) (member (car entry) my/project--auto-only))
                     project--list)))
    (apply fn args)))

(defun my/project--claim-manual (root)
  "Stop treating ROOT as generated, so it can be saved to `project-list-file'."
  (setq my/project--auto-only (delete root my/project--auto-only)))

(use-package project :ensure nil ; built-in
  :defer t
  :custom
  (project-vc-extra-root-markers '(".project"))
  (project-list-exclude '("/\\.emacs\\.d/elpa/"
                          "/\\.emacs\\.d/eln-cache/"
                          "/\\.vim/plugged/"
                          "/\\.zsh_plugins/"))
  :config
  (advice-add 'project--read-project-list :after #'my/project--merge-auto)
  (advice-add 'project--write-project-list :around #'my/project--write-manual-only)
  ;; The list may already have been read without the merge, for the reason in the comment above.
  (setq project--list 'unset))

;;;; Discovery

(defvar my/project--marker-cache nil
  "Cons of (MARKER-LIST . REGEXP), so the regexp is rebuilt only when needed.")

(defun my/project--marker-regexp ()
  "Return a regexp matching the name of any project root marker."
  (let ((markers (append my/project-root-markers project-vc-extra-root-markers)))
    (unless (equal (car my/project--marker-cache) markers)
      (setq my/project--marker-cache
            (cons (copy-sequence markers)
                  (concat "\\`\\(?:"
                          (mapconcat (lambda (m) (format "\\(?:%s\\)" (wildcard-to-regexp m)))
                                     markers "\\|")
                          "\\)\\'"))))
    (cdr my/project--marker-cache)))

(defun my/project--excluded-p (root)
  "Return non-nil if ROOT matches a regexp in `project-list-exclude'."
  (seq-some (lambda (rule)
              (and (stringp rule) (string-match-p rule root)))
            project-list-exclude))

(defun my/project--scan (dir depth acc prune-re marker-re)
  "Collect project roots at or below DIR onto ACC, descending DEPTH levels."
  (let ((entries (condition-case nil
                     (directory-files-and-attributes dir nil nil t)
                   (file-error nil))))
    (cond
     ((null entries) acc)
     ((seq-some (lambda (e) (string-match-p marker-re (car e))) entries)
      (cons (my/project--normalize dir) acc))
     ((and depth (<= depth 0)) acc)
     (t
      (dolist (entry entries acc)
        (let ((name (car entry)))
          ;; `(eq t (cadr entry))' is "a real directory": `file-attributes' gives t for one.
          (when (and (eq t (cadr entry))
                     (not (string-prefix-p "." name))
                     (not (string-match-p prune-re name)))
            (setq acc (my/project--scan (expand-file-name name dir)
                                        (and depth (1- depth))
                                        acc prune-re marker-re)))))))))

(defun my/project-discover (&optional quiet)
  "Scan `my/project-search-paths' for projects and record what was found."
  (interactive)
  (require 'project)
  (let ((found nil)
        (prune-re (my/project--prune-regexp))
        (marker-re (my/project--marker-regexp)))
    (dolist (entry my/project-search-paths)
      (setq found (my/project--scan
                   (expand-file-name (if (consp entry) (car entry) entry))
                   (if (consp entry) (cdr entry) my/project-scan-max-depth)
                   found prune-re marker-re)))
    (setq found (sort (delete-dups (seq-remove #'my/project--excluded-p found))
                      #'string<))
    (let ((added (seq-difference found (my/project--read-auto-roots))))
      (my/project--write-auto-roots found)
      ;; Re-read so the merge advice picks the new file up right away.
      (project--read-project-list)
      (cond
       ((not quiet)
        (message "%d project%s found, %d new"
                 (length found) (if (= 1 (length found)) "" "s") (length added)))
       (added
        (message "%d new project%s discovered"
                 (length added) (if (= 1 (length added)) "" "s")))))
    found))

;;;; Refreshing at startup

(defvar my/project-refresh-idle-delay 1
  "Seconds of idle time before the startup scan runs, nil to disable it.")

(defun my/project--refresh-at-startup ()
  "Schedule a one-shot `my/project-discover' after startup."
  (when (and my/project-refresh-idle-delay (not noninteractive))
    (run-with-idle-timer my/project-refresh-idle-delay nil
                         #'my/project-discover t)))

(add-hook 'after-init-hook #'my/project--refresh-at-startup)

;;;; Adding, removing, editing

(defun my/add-project (dir)
  "Add DIR to the hand-edited project list in `project-list-file'."
  (interactive (list (read-directory-name "Add project: " default-directory nil t)))
  (require 'project)
  (let* ((dir (file-name-as-directory (expand-file-name dir)))
         (pr (project-current nil dir)))
    (unless pr
      (when (y-or-n-p (format "%s is not a project.  Create a .project marker? "
                              (abbreviate-file-name dir)))
        (write-region "" nil (expand-file-name ".project" dir) nil 'silent)
        ;; `project-try-vc' caches misses as `none'.
        (project--clear-cache)
        (setq pr (project-current nil dir))))
    ;; Discovery may already know this one; pinning it by hand takes priority.
    (my/project--claim-manual (my/project--normalize dir))
    (if pr
        (progn (project-remember-project pr)
               (message "Added %s" (abbreviate-file-name dir)))
      (project--remember-dir dir)
      (message "Added %s -- no project marker, so project commands won't work inside it"
               (abbreviate-file-name dir)))))

(defun my/delete-project (root)
  "Remove ROOT from the known project list."
  (interactive
   (progn (require 'project)
          (list (project-prompt-project-dir "Delete project: " nil t))))
  (require 'project)
  (let ((root (my/project--normalize root))
        (auto (my/project--read-auto-roots)))
    (when (member root auto)
      (my/project--write-auto-roots (delete root auto)))
    (project-forget-project root)
    (project--read-project-list)))

(defun my/project--reload-list ()
  "Re-read `project-list-file' into `project--list'."
  (project--read-project-list)
  (message "Project list reloaded: %d known" (length project--list)))

(defun my/edit-projects (&optional generated)
  "Open `project-list-file' for hand editing."
  (interactive "P")
  (require 'project)
  (if generated
      (if (file-exists-p my/project-auto-file)
          (find-file-read-only my/project-auto-file)
        (user-error "Nothing discovered yet; run `my/project-discover' first"))
    (unless (file-exists-p project-list-file)
      (with-temp-file project-list-file
        (insert ";;; -*- lisp-data -*-\n()\n")))
    (find-file project-list-file)
    (add-hook 'after-save-hook #'my/project--reload-list nil t)))

;;; proj.el ends here
