;;; base2tone-suburb-light-theme.el --- Base2Tone-Suburb (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-suburb.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-suburb-light-colors
  '(
    :a0   "#1e202f"
    :a1   "#292c3d"
    :a2   "#444864"
    :a3   "#4f5472"
    :a4   "#5b6080"
    :a5   "#6e7396"
    :a6   "#878ba6"
    :a7   "#9fa2b7"
    :b0   "#5165e6"
    :b1   "#6375ee"
    :b2   "#7586f5"
    :b3   "#8696fd"
    :b4   "#a0acfe"
    :b5   "#b9c2fe"
    :b6   "#d2d8fe"
    :b7   "#ebedff"
    :c0   "#7a7175"
    :c1   "#8d8186"
    :c2   "#9f9398"
    :c3   "#b0a6aa"
    :c4   "#c2b7bc"
    :c5   "#d7cbd0"
    :c6   "#eae1e5"
    :c7   "#fbf9fa"
    :d0   "#d14781"
    :d1   "#e44e8c"
    :d2   "#f25a99"
    :d3   "#f764a1"
    :d4   "#fb6fa9"
    :d5   "#fe81b5"
    :d6   "#ff99c3"
    :d7   "#ffb3d2")
  "Swatch palette for base2tone-suburb-light.")

(deftheme base2tone-suburb-light "Base2Tone-Suburb (Light).")
(base2tone-theme-define 'base2tone-suburb-light base2tone-suburb-light-colors 'light)
(provide-theme 'base2tone-suburb-light)
(provide 'base2tone-suburb-light-theme)
;;; base2tone-suburb-light-theme.el ends here
