;;; base2tone-desert-dark-theme.el --- Base2Tone-Desert (Dark) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-desert.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-desert-dark-colors
  '(
    :a0   "#292724"
    :a1   "#3d3a34"
    :a2   "#615c51"
    :a3   "#7e7767"
    :a4   "#908774"
    :a5   "#9f9684"
    :a6   "#ada594"
    :a7   "#bbb4a5"
    :b0   "#5c523d"
    :b1   "#6e6045"
    :b2   "#816f4b"
    :b3   "#957e50"
    :b4   "#ac8e53"
    :b5   "#c6ad7b"
    :b6   "#ddcba6"
    :b7   "#f2ead9"
    :c0   "#847b75"
    :c1   "#978d87"
    :c2   "#a89f99"
    :c3   "#b9b1ac"
    :c4   "#cac3be"
    :c5   "#dcd5d0"
    :c6   "#ede7e3"
    :c7   "#fbfaf9"
    :d0   "#bc672f"
    :d1   "#d37231"
    :d2   "#dd7c3c"
    :d3   "#e58748"
    :d4   "#ec9255"
    :d5   "#f29d63"
    :d6   "#f8a872"
    :d7   "#ffb380")
  "Swatch palette for base2tone-desert-dark.")

(deftheme base2tone-desert-dark "Base2Tone-Desert (Dark).")
(base2tone-theme-define 'base2tone-desert-dark base2tone-desert-dark-colors 'dark)
(provide-theme 'base2tone-desert-dark)
(provide 'base2tone-desert-dark-theme)
;;; base2tone-desert-dark-theme.el ends here
