;;; base2tone-pool-light-theme.el --- Base2Tone-Pool (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-pool.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-pool-light-colors
  '(
    :a0   "#2a2433"
    :a1   "#372f42"
    :a2   "#574b68"
    :a3   "#635775"
    :a4   "#706383"
    :a5   "#857897"
    :a6   "#9a90a7"
    :a7   "#afa7b9"
    :b0   "#8f51e6"
    :b1   "#9d63ee"
    :b2   "#aa75f5"
    :b3   "#b886fd"
    :b4   "#c7a0fe"
    :b5   "#d6b9fe"
    :b6   "#e4d2fe"
    :b7   "#f3ebff"
    :c0   "#7a7171"
    :c1   "#8d8281"
    :c2   "#9f9393"
    :c3   "#b0a6a6"
    :c4   "#c2b8b7"
    :c5   "#d7cccb"
    :c6   "#eae1e1"
    :c7   "#fbf9f9"
    :d0   "#cf504a"
    :d1   "#d95f59"
    :d2   "#ed655e"
    :d3   "#f36f68"
    :d4   "#f87972"
    :d5   "#fc8983"
    :d6   "#ff9e99"
    :d7   "#ffb6b3")
  "Swatch palette for base2tone-pool-light.")

(deftheme base2tone-pool-light "Base2Tone-Pool (Light).")
(base2tone-theme-define 'base2tone-pool-light base2tone-pool-light-colors 'light)
(provide-theme 'base2tone-pool-light)
(provide 'base2tone-pool-light-theme)
;;; base2tone-pool-light-theme.el ends here
