;;; base2tone-garden-dark-theme.el --- Base2Tone-Garden (Dark) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-garden.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-garden-dark-colors
  '(
    :a0   "#1e1f1e"
    :a1   "#2b2c2a"
    :a2   "#505350"
    :a3   "#5d605c"
    :a4   "#696d69"
    :a5   "#828782"
    :a6   "#969c96"
    :a7   "#aab1aa"
    :b0   "#1c8217"
    :b1   "#25931f"
    :b2   "#3fac39"
    :b3   "#4cb946"
    :b4   "#6bcc66"
    :b5   "#90d98c"
    :b6   "#b7e3b5"
    :b7   "#dcf0db"
    :c0   "#837467"
    :c1   "#978678"
    :c2   "#a7988b"
    :c3   "#b7aa9f"
    :c4   "#c7bcb2"
    :c5   "#dbd0c7"
    :c6   "#ece5df"
    :c7   "#fbfaf8"
    :d0   "#bd5d0f"
    :d1   "#c96a1d"
    :d2   "#d97726"
    :d3   "#dd843c"
    :d4   "#db9257"
    :d5   "#dba070"
    :d6   "#d9af8c"
    :d7   "#e0cab8")
  "Swatch palette for base2tone-garden-dark.")

(deftheme base2tone-garden-dark "Base2Tone-Garden (Dark).")
(base2tone-theme-define 'base2tone-garden-dark base2tone-garden-dark-colors 'dark)
(provide-theme 'base2tone-garden-dark)
(provide 'base2tone-garden-dark-theme)
;;; base2tone-garden-dark-theme.el ends here
