;;; base2tone-space-light-theme.el --- Base2Tone-Space (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-space.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-space-light-colors
  '(
    :a0   "#24242e"
    :a1   "#333342"
    :a2   "#515167"
    :a3   "#5b5b76"
    :a4   "#737391"
    :a5   "#8a8aa3"
    :a6   "#a1a1b5"
    :a7   "#b8b8c7"
    :b0   "#5151e6"
    :b1   "#6363ee"
    :b2   "#7676f4"
    :b3   "#767693"
    :b4   "#8a8aad"
    :b5   "#aaaaca"
    :b6   "#cecee3"
    :b7   "#ebebff"
    :c0   "#7b736f"
    :c1   "#8e8580"
    :c2   "#a09792"
    :c3   "#b1a9a5"
    :c4   "#c3bbb7"
    :c5   "#d8cfcb"
    :c6   "#eae4e1"
    :c7   "#fbf9f9"
    :d0   "#b25424"
    :d1   "#cb5c25"
    :d2   "#dd672c"
    :d3   "#e66e33"
    :d4   "#ec7336"
    :d5   "#f37b3f"
    :d6   "#f88349"
    :d7   "#fe8c52")
  "Swatch palette for base2tone-space-light.")

(deftheme base2tone-space-light "Base2Tone-Space (Light).")
(base2tone-theme-define 'base2tone-space-light base2tone-space-light-colors 'light)
(provide-theme 'base2tone-space-light)
(provide 'base2tone-space-light-theme)
;;; base2tone-space-light-theme.el ends here
