;;; base2tone-motel-dark-theme.el --- Base2Tone-Motel (Dark) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-motel.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-motel-dark-colors
  '(
    :a0   "#242323"
    :a1   "#373434"
    :a2   "#5a5354"
    :a3   "#766b6c"
    :a4   "#86797b"
    :a5   "#94898b"
    :a6   "#a5979a"
    :a7   "#b3a8aa"
    :b0   "#674c50"
    :b1   "#7d5e63"
    :b2   "#956f76"
    :b3   "#a7868b"
    :b4   "#b89da2"
    :b5   "#ccb3b7"
    :b6   "#dec9cc"
    :b7   "#f0dbdf"
    :c0   "#847875"
    :c1   "#978a87"
    :c2   "#a89c99"
    :c3   "#b9aeac"
    :c4   "#cac0be"
    :c5   "#dcd2d0"
    :c6   "#ede5e3"
    :c7   "#fbf9f9"
    :d0   "#e24f32"
    :d1   "#ea5f43"
    :d2   "#f6684c"
    :d3   "#f77c64"
    :d4   "#f8917c"
    :d5   "#ffa28f"
    :d6   "#ffb3a3"
    :d7   "#ffc8bd")
  "Swatch palette for base2tone-motel-dark.")

(deftheme base2tone-motel-dark "Base2Tone-Motel (Dark).")
(base2tone-theme-define 'base2tone-motel-dark base2tone-motel-dark-colors 'dark)
(provide-theme 'base2tone-motel-dark)
(provide 'base2tone-motel-dark-theme)
;;; base2tone-motel-dark-theme.el ends here
