;;; base2tone-evening-dark-theme.el --- Base2Tone-Evening (Dark) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-evening.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-evening-dark-colors
  '(
    :a0   "#2a2734"
    :a1   "#363342"
    :a2   "#545167"
    :a3   "#6c6783"
    :a4   "#787391"
    :a5   "#8e8aa3"
    :a6   "#a4a1b5"
    :a7   "#bab8c7"
    :b0   "#6a51e6"
    :b1   "#7a63ee"
    :b2   "#8a75f5"
    :b3   "#9a86fd"
    :b4   "#afa0fe"
    :b5   "#c4b9fe"
    :b6   "#d9d2fe"
    :b7   "#eeebff"
    :c0   "#7c756e"
    :c1   "#90877f"
    :c2   "#a19991"
    :c3   "#b2aba4"
    :c4   "#c3bdb6"
    :c5   "#d8d1ca"
    :c6   "#ebe6e0"
    :c7   "#fbfaf9"
    :d0   "#b37537"
    :d1   "#cb823a"
    :d2   "#e09142"
    :d3   "#ffa142"
    :d4   "#ffad5c"
    :d5   "#ffb870"
    :d6   "#ffc285"
    :d7   "#ffcc99")
  "Swatch palette for base2tone-evening-dark.")

(deftheme base2tone-evening-dark "Base2Tone-Evening (Dark).")
(base2tone-theme-define 'base2tone-evening-dark base2tone-evening-dark-colors 'dark)
(provide-theme 'base2tone-evening-dark)
(provide 'base2tone-evening-dark-theme)
;;; base2tone-evening-dark-theme.el ends here
