;;; base2tone-drawbridge-light-theme.el --- Base2Tone-Drawbridge (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-drawbridge.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-drawbridge-light-colors
  '(
    :a0   "#1b1f32"
    :a1   "#252a41"
    :a2   "#444b6f"
    :a3   "#51587b"
    :a4   "#5e6587"
    :a5   "#797e96"
    :a6   "#9094a7"
    :a7   "#a6aab9"
    :b0   "#4961da"
    :b1   "#516aec"
    :b2   "#627af4"
    :b3   "#7289fd"
    :b4   "#8b9efd"
    :b5   "#a5b3fe"
    :b6   "#c3cdfe"
    :b7   "#e1e6ff"
    :c0   "#71787a"
    :c1   "#818b8d"
    :c2   "#939c9f"
    :c3   "#a6aeb0"
    :c4   "#b7c0c2"
    :c5   "#cbd4d7"
    :c6   "#e1e8ea"
    :c7   "#f9fbfb"
    :d0   "#289dbd"
    :d1   "#33abcc"
    :d2   "#4db0cb"
    :d3   "#5cbcd6"
    :d4   "#67c9e4"
    :d5   "#75d5f0"
    :d6   "#86e0f9"
    :d7   "#99e9ff")
  "Swatch palette for base2tone-drawbridge-light.")

(deftheme base2tone-drawbridge-light "Base2Tone-Drawbridge (Light).")
(base2tone-theme-define 'base2tone-drawbridge-light base2tone-drawbridge-light-colors 'light)
(provide-theme 'base2tone-drawbridge-light)
(provide 'base2tone-drawbridge-light-theme)
;;; base2tone-drawbridge-light-theme.el ends here
