;;; base2tone-heath-dark-theme.el --- Base2Tone-Heath (Dark) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-heath.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-heath-dark-colors
  '(
    :a0   "#222022"
    :a1   "#2f2d2f"
    :a2   "#575158"
    :a3   "#635f63"
    :a4   "#6f6b70"
    :a5   "#89858a"
    :a6   "#9e999f"
    :a7   "#b3adb3"
    :b0   "#a21fad"
    :b1   "#845e87"
    :b2   "#8f6c93"
    :b3   "#9a819c"
    :b4   "#cb79d2"
    :b5   "#db8de2"
    :b6   "#eaa8f0"
    :b7   "#fdebff"
    :c0   "#787673"
    :c1   "#8b8884"
    :c2   "#9d9a95"
    :c3   "#aeaba7"
    :c4   "#c1bdb9"
    :c5   "#d6d2cc"
    :c6   "#eae6e1"
    :c7   "#fbfaf9"
    :d0   "#995900"
    :d1   "#aa6709"
    :d2   "#b87414"
    :d3   "#c38022"
    :d4   "#cc8c33"
    :d5   "#d9b98c"
    :d6   "#e6c699"
    :d7   "#ffd599")
  "Swatch palette for base2tone-heath-dark.")

(deftheme base2tone-heath-dark "Base2Tone-Heath (Dark).")
(base2tone-theme-define 'base2tone-heath-dark base2tone-heath-dark-colors 'dark)
(provide-theme 'base2tone-heath-dark)
(provide 'base2tone-heath-dark-theme)
;;; base2tone-heath-dark-theme.el ends here
