;;; base2tone-sea-dark-theme.el --- Base2Tone-Sea (Dark) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-sea.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-sea-dark-colors
  '(
    :a0   "#1d262f"
    :a1   "#27323f"
    :a2   "#405368"
    :a3   "#4a5f78"
    :a4   "#738191"
    :a5   "#8a96a3"
    :a6   "#a1aab5"
    :a7   "#b8bfc7"
    :b0   "#004a9e"
    :b1   "#1757a1"
    :b2   "#34659d"
    :b3   "#57718e"
    :b4   "#6e9bcf"
    :b5   "#7eb6f6"
    :b6   "#afd4fe"
    :b7   "#ebf4ff"
    :c0   "#717a77"
    :c1   "#818d89"
    :c2   "#939f9b"
    :c3   "#a6b0ad"
    :c4   "#b7c2be"
    :c5   "#cbd7d3"
    :c6   "#e1eae7"
    :c7   "#f9fbfa"
    :d0   "#067953"
    :d1   "#088c60"
    :d2   "#0aa370"
    :d3   "#0db57d"
    :d4   "#0fc78a"
    :d5   "#14e19d"
    :d6   "#2aeaaa"
    :d7   "#47ebb4")
  "Swatch palette for base2tone-sea-dark.")

(deftheme base2tone-sea-dark "Base2Tone-Sea (Dark).")
(base2tone-theme-define 'base2tone-sea-dark base2tone-sea-dark-colors 'dark)
(provide-theme 'base2tone-sea-dark)
(provide 'base2tone-sea-dark-theme)
;;; base2tone-sea-dark-theme.el ends here
