;;; base2tone-lavender-dark-theme.el --- Base2Tone-Lavender (Dark) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-lavender.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-lavender-dark-colors
  '(
    :a0   "#201d2a"
    :a1   "#2c2839"
    :a2   "#4b455f"
    :a3   "#625a7c"
    :a4   "#6e658b"
    :a5   "#827a9f"
    :a6   "#9992b0"
    :a7   "#afa9c1"
    :b0   "#7451e6"
    :b1   "#8363ee"
    :b2   "#9375f5"
    :b3   "#a286fd"
    :b4   "#b5a0fe"
    :b5   "#c9b9fe"
    :b6   "#dcd2fe"
    :b7   "#efebff"
    :c0   "#7c6f85"
    :c1   "#8e8198"
    :c2   "#a092aa"
    :c3   "#b2a4bc"
    :c4   "#c4b6ce"
    :c5   "#d8cce0"
    :c6   "#ece4f1"
    :c7   "#faf8fc"
    :d0   "#b042ff"
    :d1   "#b957ff"
    :d2   "#c16bff"
    :d3   "#ca80ff"
    :d4   "#d294ff"
    :d5   "#dba8ff"
    :d6   "#e3bdff"
    :d7   "#ecd1ff")
  "Swatch palette for base2tone-lavender-dark.")

(deftheme base2tone-lavender-dark "Base2Tone-Lavender (Dark).")
(base2tone-theme-define 'base2tone-lavender-dark base2tone-lavender-dark-colors 'dark)
(provide-theme 'base2tone-lavender-dark)
(provide 'base2tone-lavender-dark-theme)
;;; base2tone-lavender-dark-theme.el ends here
