;;; base2tone-cave-light-theme.el --- Base2Tone-Cave (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-cave.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-cave-light-colors
  '(
    :a0   "#222021"
    :a1   "#2f2d2e"
    :a2   "#565254"
    :a3   "#635f60"
    :a4   "#706b6d"
    :a5   "#8a8586"
    :a6   "#9f999b"
    :a7   "#b3adaf"
    :b0   "#ad1f51"
    :b1   "#875e6d"
    :b2   "#936c7a"
    :b3   "#9c818b"
    :b4   "#d27998"
    :b5   "#e28dab"
    :b6   "#f0a8c1"
    :b7   "#ffebf2"
    :c0   "#787673"
    :c1   "#8b8984"
    :c2   "#9d9b95"
    :c3   "#aeaca7"
    :c4   "#c1beb9"
    :c5   "#d6d3cc"
    :c6   "#eae7e1"
    :c7   "#fbfaf9"
    :d0   "#996e00"
    :d1   "#aa7c09"
    :d2   "#b88914"
    :d3   "#c39622"
    :d4   "#cca133"
    :d5   "#ddaf3c"
    :d6   "#ebbc47"
    :d7   "#ffcc4d")
  "Swatch palette for base2tone-cave-light.")

(deftheme base2tone-cave-light "Base2Tone-Cave (Light).")
(base2tone-theme-define 'base2tone-cave-light base2tone-cave-light-colors 'light)
(provide-theme 'base2tone-cave-light)
(provide 'base2tone-cave-light-theme)
;;; base2tone-cave-light-theme.el ends here
