;;; base2tone-earth-light-theme.el --- Base2Tone-Earth (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-earth.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-earth-light-colors
  '(
    :a0   "#322d29"
    :a1   "#3f3a37"
    :a2   "#5b534d"
    :a3   "#6a5f58"
    :a4   "#796b63"
    :a5   "#a3948a"
    :a6   "#b5a9a1"
    :a7   "#c7beb8"
    :b0   "#6f5849"
    :b1   "#786254"
    :b2   "#816d5f"
    :b3   "#88786d"
    :b4   "#967e6e"
    :b5   "#a48774"
    :b6   "#dfb99f"
    :b7   "#fff3eb"
    :c0   "#736d5e"
    :c1   "#88806d"
    :c2   "#9a927e"
    :c3   "#aaa392"
    :c4   "#bbb4a5"
    :c5   "#cfc9b9"
    :c6   "#e2dcd0"
    :c7   "#f2efe8"
    :d0   "#9c8349"
    :d1   "#b3944d"
    :d2   "#bfa05a"
    :d3   "#cda956"
    :d4   "#d9b154"
    :d5   "#e6b84d"
    :d6   "#f1be46"
    :d7   "#fcc440")
  "Swatch palette for base2tone-earth-light.")

(deftheme base2tone-earth-light "Base2Tone-Earth (Light).")
(base2tone-theme-define 'base2tone-earth-light base2tone-earth-light-colors 'light)
(provide-theme 'base2tone-earth-light)
(provide 'base2tone-earth-light-theme)
;;; base2tone-earth-light-theme.el ends here
