;;; base2tone-mall-light-theme.el --- Base2Tone-Mall (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-mall.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-mall-light-colors
  '(
    :a0   "#1e1e1f"
    :a1   "#2b2b2c"
    :a2   "#515053"
    :a3   "#5e5c60"
    :a4   "#6a686e"
    :a5   "#838188"
    :a6   "#97959d"
    :a7   "#acaab1"
    :b0   "#855ee8"
    :b1   "#936df3"
    :b2   "#a17efc"
    :b3   "#b294ff"
    :b4   "#c5adff"
    :b5   "#d3c2ff"
    :b6   "#e5dbff"
    :b7   "#f4f0ff"
    :c0   "#6d767e"
    :c1   "#7e8891"
    :c2   "#909aa2"
    :c3   "#a2abb3"
    :c4   "#b5bdc4"
    :c5   "#c8d2da"
    :c6   "#dee6ed"
    :c7   "#f8fafc"
    :d0   "#3692e2"
    :d1   "#479eeb"
    :d2   "#5aabf2"
    :d3   "#69b5f7"
    :d4   "#75bfff"
    :d5   "#8ac8ff"
    :d6   "#9ed2ff"
    :d7   "#b3dbff")
  "Swatch palette for base2tone-mall-light.")

(deftheme base2tone-mall-light "Base2Tone-Mall (Light).")
(base2tone-theme-define 'base2tone-mall-light base2tone-mall-light-colors 'light)
(provide-theme 'base2tone-mall-light)
(provide 'base2tone-mall-light-theme)
;;; base2tone-mall-light-theme.el ends here
