;;; base2tone-morning-light-theme.el --- Base2Tone-Morning (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-morning.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-morning-light-colors
  '(
    :a0   "#232834"
    :a1   "#31363f"
    :a2   "#4f5664"
    :a3   "#656e81"
    :a4   "#707a8f"
    :a5   "#7e889a"
    :a6   "#8d95a5"
    :a7   "#a9afbc"
    :b0   "#063289"
    :b1   "#0b3c9d"
    :b2   "#1659df"
    :b3   "#3d75e6"
    :b4   "#728fcb"
    :b5   "#93abdc"
    :b6   "#b7c9eb"
    :b7   "#dee6f7"
    :c0   "#544d40"
    :c1   "#69604f"
    :c2   "#867b65"
    :c3   "#9c927c"
    :c4   "#b6ad9a"
    :c5   "#cdc4b1"
    :c6   "#e3dcce"
    :c7   "#faf8f5"
    :d0   "#2d2006"
    :d1   "#594212"
    :d2   "#896724"
    :d3   "#9a7c42"
    :d4   "#b29762"
    :d5   "#c6b28b"
    :d6   "#d1c2a3"
    :d7   "#e5ddcd")
  "Swatch palette for base2tone-morning-light.")

(deftheme base2tone-morning-light "Base2Tone-Morning (Light).")
(base2tone-theme-define 'base2tone-morning-light base2tone-morning-light-colors 'light)
(provide-theme 'base2tone-morning-light)
(provide 'base2tone-morning-light-theme)
;;; base2tone-morning-light-theme.el ends here
