;;; base2tone-porch-light-theme.el --- Base2Tone-Porch (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-porch.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-porch-light-colors
  '(
    :a0   "#221e24"
    :a1   "#302a32"
    :a2   "#574e5a"
    :a3   "#645a68"
    :a4   "#716774"
    :a5   "#8b808e"
    :a6   "#9f95a3"
    :a7   "#b3aab5"
    :b0   "#674573"
    :b1   "#7e548c"
    :b2   "#9466a3"
    :b3   "#a77cb6"
    :b4   "#ba95c6"
    :b5   "#cdacd7"
    :b6   "#dfcbe6"
    :b7   "#f2e3f7"
    :c0   "#7e736d"
    :c1   "#91857e"
    :c2   "#a29790"
    :c3   "#b3a9a2"
    :c4   "#c4bbb5"
    :c5   "#dacfc8"
    :c6   "#ede3de"
    :c7   "#fcf9f8"
    :d0   "#c46731"
    :d1   "#d97136"
    :d2   "#e17f47"
    :d3   "#ec8d55"
    :d4   "#f39b68"
    :d5   "#f8aa7c"
    :d6   "#fcb58d"
    :d7   "#ffc29e")
  "Swatch palette for base2tone-porch-light.")

(deftheme base2tone-porch-light "Base2Tone-Porch (Light).")
(base2tone-theme-define 'base2tone-porch-light base2tone-porch-light-colors 'light)
(provide-theme 'base2tone-porch-light)
(provide 'base2tone-porch-light-theme)
;;; base2tone-porch-light-theme.el ends here
