;;; base2tone-forest-light-theme.el --- Base2Tone-Forest (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-forest.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-forest-light-colors
  '(
    :a0   "#2a2d2a"
    :a1   "#353b35"
    :a2   "#485148"
    :a3   "#535f53"
    :a4   "#5e6e5e"
    :a5   "#687d68"
    :a6   "#a1b5a1"
    :a7   "#b8c7b8"
    :b0   "#435643"
    :b1   "#4f634f"
    :b2   "#5c705c"
    :b3   "#687d68"
    :b4   "#8fae8f"
    :b5   "#b3d6b3"
    :b6   "#c8e4c8"
    :b7   "#f0fff0"
    :c0   "#7d816a"
    :c1   "#90947a"
    :c2   "#a1a58d"
    :c3   "#b2b5a1"
    :c4   "#c3c6b3"
    :c5   "#d7dac8"
    :c6   "#eaecdf"
    :c7   "#fbfbf8"
    :d0   "#656b47"
    :d1   "#818b4b"
    :d2   "#a2b34d"
    :d3   "#b1c44f"
    :d4   "#bfd454"
    :d5   "#cbe25a"
    :d6   "#daf06a"
    :d7   "#e5fb79")
  "Swatch palette for base2tone-forest-light.")

(deftheme base2tone-forest-light "Base2Tone-Forest (Light).")
(base2tone-theme-define 'base2tone-forest-light base2tone-forest-light-colors 'light)
(provide-theme 'base2tone-forest-light)
(provide 'base2tone-forest-light-theme)
;;; base2tone-forest-light-theme.el ends here
