;;; base2tone-field-dark-theme.el --- Base2Tone-Field (Dark) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-field.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-field-dark-colors
  '(
    :a0   "#18201e"
    :a1   "#242e2c"
    :a2   "#42524f"
    :a3   "#5a6d6a"
    :a4   "#667a77"
    :a5   "#78918d"
    :a6   "#8ea4a0"
    :a7   "#a4b7b4"
    :b0   "#037764"
    :b1   "#089b83"
    :b2   "#0fbda0"
    :b3   "#25d0b4"
    :b4   "#40ddc3"
    :b5   "#65e6d1"
    :b6   "#88f2e0"
    :b7   "#a8fff1"
    :c0   "#68736d"
    :c1   "#78877e"
    :c2   "#8a9990"
    :c3   "#9daaa2"
    :c4   "#aebcb4"
    :c5   "#c7d1cb"
    :c6   "#e3e8e5"
    :c7   "#f9fbfa"
    :d0   "#00943e"
    :d1   "#0eaa4f"
    :d2   "#15c15d"
    :d3   "#25d46e"
    :d4   "#3be381"
    :d5   "#55ec94"
    :d6   "#69f7a4"
    :d7   "#85ffb8")
  "Swatch palette for base2tone-field-dark.")

(deftheme base2tone-field-dark "Base2Tone-Field (Dark).")
(base2tone-theme-define 'base2tone-field-dark base2tone-field-dark-colors 'dark)
(provide-theme 'base2tone-field-dark)
(provide 'base2tone-field-dark-theme)
;;; base2tone-field-dark-theme.el ends here
