;;; base2tone-lake-light-theme.el --- Base2Tone-Lake (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-lake.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-lake-light-colors
  '(
    :a0   "#192d34"
    :a1   "#223c44"
    :a2   "#335966"
    :a3   "#3d6876"
    :a4   "#467686"
    :a5   "#508495"
    :a6   "#7ba8b7"
    :a7   "#adc8d1"
    :b0   "#2f7289"
    :b1   "#36829b"
    :b2   "#3e91ac"
    :b3   "#499fbc"
    :b4   "#62b1cb"
    :b5   "#7dc2d9"
    :b6   "#a5d8e9"
    :b7   "#e1f7ff"
    :c0   "#7a7971"
    :c1   "#8d8c81"
    :c2   "#9f9d93"
    :c3   "#b1afa5"
    :c4   "#c2c1b7"
    :c5   "#d5d4cd"
    :c6   "#e8e7e3"
    :c7   "#fafaf9"
    :d0   "#84740b"
    :d1   "#978611"
    :d2   "#b7a21a"
    :d3   "#c4b031"
    :d4   "#cbbb4d"
    :d5   "#d6c65c"
    :d6   "#e9d763"
    :d7   "#ffeb66")
  "Swatch palette for base2tone-lake-light.")

(deftheme base2tone-lake-light "Base2Tone-Lake (Light).")
(base2tone-theme-define 'base2tone-lake-light base2tone-lake-light-colors 'light)
(provide-theme 'base2tone-lake-light)
(provide 'base2tone-lake-light-theme)
;;; base2tone-lake-light-theme.el ends here
