;;; base2tone-meadow-light-theme.el --- Base2Tone-Meadow (Light) -*- no-byte-compile: t; lexical-binding: t; -*-
;;; Commentary:
;; Generated by gen-base2tone.el from palettes/base2tone-meadow.yml.
;; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.
;;; Code:

(require 'base2tone-theme)

(defvar base2tone-meadow-light-colors
  '(
    :a0   "#192834"
    :a1   "#223644"
    :a2   "#335166"
    :a3   "#3d5e76"
    :a4   "#466b86"
    :a5   "#507895"
    :a6   "#7b9eb7"
    :a7   "#7b9eb7"
    :b0   "#1b6498"
    :b1   "#2172ab"
    :b2   "#277fbe"
    :b3   "#4299d7"
    :b4   "#47adf5"
    :b5   "#8dcefc"
    :b6   "#afddfe"
    :b7   "#d1ecff"
    :c0   "#757b6f"
    :c1   "#878e80"
    :c2   "#99a092"
    :c3   "#abb1a5"
    :c4   "#bdc3b7"
    :c5   "#d1d6cd"
    :c6   "#e6e8e3"
    :c7   "#fafbf9"
    :d0   "#4d8217"
    :d1   "#59931f"
    :d2   "#66a329"
    :d3   "#73b234"
    :d4   "#80bf40"
    :d5   "#8cdd3c"
    :d6   "#99eb47"
    :d7   "#a6f655")
  "Swatch palette for base2tone-meadow-light.")

(deftheme base2tone-meadow-light "Base2Tone-Meadow (Light).")
(base2tone-theme-define 'base2tone-meadow-light base2tone-meadow-light-colors 'light)
(provide-theme 'base2tone-meadow-light)
(provide 'base2tone-meadow-light-theme)
;;; base2tone-meadow-light-theme.el ends here
