;;; gen-base2tone.el --- Generate Base2Tone theme files -*- no-byte-compile: t; lexical-binding: t; -*-

;;; Commentary:

;; Batch generator.  Reads every Base2Tone scheme YAML in ./palettes/ and, for
;; each, writes two thin loadable theme files (dark + light) that delegate all
;; face work to `base2tone-theme-define' in base2tone-theme.el.
;;
;; Run from this directory:
;;   emacs --batch -l gen-base2tone.el
;;
;; The Base2Tone YAML is flat (`baseA0: "2a2734"'), so it is parsed with a
;; regexp -- no YAML library required.

;;; Code:

(require 'cl-lib)

(defconst gen-base2tone--dir
  (file-name-directory (or load-file-name buffer-file-name default-directory))
  "Directory containing this generator (the package root).")

(defun gen-base2tone--read-palette (file)
  "Parse Base2Tone scheme FILE into (SCHEME-NAME . COLORS-PLIST).
Swatch keys baseA0..baseD7 become keywords :a0..:d7 with `#'-prefixed hex."
  (with-temp-buffer
    (insert-file-contents file)
    (let ((scheme nil) (colors nil))
      (goto-char (point-min))
      (when (re-search-forward "^scheme:[ \t]*\"\\([^\"]+\\)\"" nil t)
        (setq scheme (match-string 1)))
      (goto-char (point-min))
      (while (re-search-forward
              "^base\\([A-D][0-7]\\):[ \t]*\"?\\([0-9A-Fa-f]\\{6\\}\\)\"?" nil t)
        (let ((key (intern (concat ":" (downcase (match-string 1)))))
              (hex (concat "#" (downcase (match-string 2)))))
          (setq colors (plist-put colors key hex))))
      (cons scheme colors))))

(defun gen-base2tone--plist->string (colors)
  "Pretty-print swatch plist COLORS as aligned theme-file source."
  (let (lines)
    (cl-loop for (k v) on colors by #'cddr
             do (push (format "    %-5s \"%s\"" k v) lines))
    (concat "(\n" (mapconcat #'identity (nreverse lines) "\n") ")")))

(defun gen-base2tone--write-theme (scheme-slug human variant colors)
  "Write one theme file for SCHEME-SLUG / VARIANT using COLORS.
HUMAN is the display name (e.g. \"Base2Tone Evening\")."
  (let* ((name (format "base2tone-%s-%s" scheme-slug variant))
         (var  (format "%s-colors" name))
         (file (expand-file-name (format "%s-theme.el" name) gen-base2tone--dir))
         (cap  (capitalize (symbol-name variant))))
    (with-temp-file file
      (insert
       (format ";;; %s-theme.el --- %s (%s) -*- lexical-binding: t -*-\n" name human cap)
       ";;; Commentary:\n"
       (format ";; Generated by gen-base2tone.el from palettes/base2tone-%s.yml.\n" scheme-slug)
       ";; Do not edit by hand; edit the palette or base2tone-theme.el and regenerate.\n"
       ";;; Code:\n\n"
       "(require 'base2tone-theme)\n\n"
       (format "(defvar %s\n  '%s\n  \"Swatch palette for %s.\")\n\n"
               var (gen-base2tone--plist->string colors) name)
       (format "(deftheme %s \"%s (%s).\")\n" name human cap)
       (format "(base2tone-theme-define '%s %s '%s)\n" name var variant)
       (format "(provide-theme '%s)\n" name)
       (format "(provide '%s-theme)\n" name)
       (format ";;; %s-theme.el ends here\n" name)))
    file))

(defun gen-base2tone-generate ()
  "Generate dark + light theme files for every palette."
  (let ((palettes (directory-files
                   (expand-file-name "palettes" gen-base2tone--dir)
                   t "\\`base2tone-.*\\.yml\\'"))
        (count 0))
    (dolist (file palettes)
      (let* ((parsed (gen-base2tone--read-palette file))
             (human  (or (car parsed)
                         (file-name-base file)))
             (colors (cdr parsed))
             (slug   (replace-regexp-in-string
                      "\\`base2tone-" ""
                      (file-name-base file))))
        (dolist (variant '(dark light))
          (gen-base2tone--write-theme slug human variant colors)
          (setq count (1+ count)))))
    (message "Generated %d theme files from %d palettes." count (length palettes))))

(gen-base2tone-generate)

(provide 'gen-base2tone)
;;; gen-base2tone.el ends here
