(cond
 ((eq system-type 'windows-nt)
  (when (member "Consolas" (font-family-list))
    (set-frame-font "Consolas 12" t t)
    (set-face-attribute 'fixed-pitch nil :family "Consolas")
    (set-face-attribute 'variable-pitch nil :family "Calibri")))
 ((eq system-type 'darwin)
  (when (member "Menlo" (font-family-list))
    (set-frame-font "Menlo 12" t t)
    (set-face-attribute 'fixed-pitch nil :family "Menlo")
    (set-face-attribute 'variable-pitch nil :family "Helvetica Neue")))
 ((eq system-type 'gnu/linux)
  (when (member "DejaVu Sans Mono" (font-family-list))
    (set-frame-font "DejaVu Sans Mono 12" t t)
    (set-face-attribute 'fixed-pitch nil :family "DejaVu Sans Mono")
    (set-face-attribute 'variable-pitch nil :family "DejaVu Sans"))))
